/**
 * @file mcp3204_example.cpp
 *
 * @brief Example of using libsetila library on Raspberry Pi for communication
 * with MCP3204 AD converter. An analog signal generated by TMP36 temperature
 * sensor is converted by the MCP3204 to a digital value that is transferred to
 * Raspberry Pi for calculating the actual temperature value.
 *
 * @author Goce Boshkovski
 *
 * @copyright GNU General Public License v3
 */

#include <iostream>
#include <memory>

#include "setila/mcp3204.h"

float TMP36_temperature(float);

int main() {

  std::unique_ptr<SPI_Bus_Master_Device> spi_bus_master{
      new SPI_Bus_Master_Device("/dev/spidev0.1")};

  constexpr float reference_voltage{2.491};
  std::unique_ptr<MCP3204> ad_MCP3204{new MCP3204(reference_voltage)};

  int status{0};

  if (spi_bus_master->open_bus()) {
    std::cout << "Failed to open bus master device.\n";
    return -1;
  }

  if (spi_bus_master->configure(SPI_BUS_MODE::MODE_0, MCP3204::SPI_BUS_SPEED,
                                MCP3204::SPI_BITS_PER_WORD, 0)) {
    std::cout << "Setting SPI bus master parameters failed.\n";
    return status;
  }

  if (ad_MCP3204->attach_to_bus(spi_bus_master.get())) {
    std::cout << "Attach to SPI bus master failed.\n";
    return status;
  }

  status = ad_MCP3204->convert(MCP3204::INPUT_CHANNEL::CH0,
                               MCP3204::INPUT_CHANNEL_MODE::SINGLE_ENDED);

  if (status) {
    std::cout << "MCP3204 Error: communication error while asking for AD "
                 "conversion. Error code: "
              << status << '\n';
    return status;
  }

  std::cout << "Digital value of the sensor reading: "
            << ad_MCP3204->digital_value() << '\n';
  std::cout << "Analog value: " << ad_MCP3204->analog_value() << "V\n";
  std::cout << "Temperature t = "
            << TMP36_temperature(ad_MCP3204->analog_value()) << "[°C]\n";

  ad_MCP3204->dettach_from_master_bus();

  spi_bus_master->close_bus();

  return status;
}

float TMP36_temperature(float voltage_level) {
  return (voltage_level * 1000 - 500) / 10;
}
